services:
  - type: web
    name: smartvax
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
